#!/usr/bin/env python3
import nose2
import sys
import hilbert as h
if __name__ == "__main__":

    if '--cpu' in sys.argv:
        print('\nTESTING DEVICE: CPU\n')
        sys.argv.remove('--cpu')
        h.CONSTANTS.MATRIX_DEVICE = 'cpu'
    else:
        print('\nTESTING DEVICE: CUDA.  Use --cpu to test on cpu.\n')

    if '-v' in sys.argv:
        VERBOSE = True

    nose2.discover()
